version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2
    working_directory: ~/circleci-eks-demo

    steps:
      - checkout
      - run: 
          name: Install aws cli
          command: |
            sudo pip install awscli
            echo "export AWS_REGION=us-east-1" >> $BASH_ENV
            aws --version
      - run: 
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
            sudo chmod +x /usr/local/bin/aws-iam-authenticator
            /usr/local/bin/aws-iam-authenticator --help
      - run: 
          name: Install kubectl
          command: |
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            sudo chmod +x /usr/local/bin/kubectl
      - run:
          name: Test AWS EKS configuration
          command: |
            aws sts get-caller-identity
            aws eks update-kubeconfig --name istio-on-eks
            kubectl apply -f httpbin.yaml
            kubectl apply -f httpbin-gateway.yaml
            kubectl rollout status deployment.v1.apps/httpbin
